/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.ClientPagePanels.ClientPageMenuPanel;
import gui.DoctorPagePanels.DoctorPageMenuPanel;

/**
 *
 * @author User
 */
public class DoctorsPage extends javax.swing.JPanel {

    /**
     * Creates new form DoctorsPage
     */
    public DoctorsPage() {
        initComponents();
        this.add(new DoctorPageMenuPanel());
        this.setVisible(true);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
