package gui;


import java.awt.Color;
import java.awt.Component;
import java.awt.Panel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author lenovo
 */
public class MainFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form MainFrame
     */
   public MainFrame() {
        initComponents();
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        line = new javax.swing.JSeparator();
        exit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        listPane = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        doctors = new javax.swing.JPanel();
        doctorsLabel = new javax.swing.JLabel();
        clients = new javax.swing.JPanel();
        clientsLabel = new javax.swing.JLabel();
        results = new javax.swing.JPanel();
        resultsLabel = new javax.swing.JLabel();
        bill = new javax.swing.JPanel();
        billLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(22, 113, 185));

        headerText.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        headerText.setForeground(new java.awt.Color(255, 255, 255));
        headerText.setText("OBAL Medical Laboratory");

        exit.setBackground(new java.awt.Color(250, 251, 252));
        exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        exit.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/llljl.PNG"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
        });
        exit.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 40, 50));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        mainPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 150));

        mainPane.setBackground(new java.awt.Color(255, 255, 255));
        mainPane.setPreferredSize(new java.awt.Dimension(1200, 930));
        mainPane.setLayout(new java.awt.CardLayout());
        mainPanel.add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 1200, 930));

        listPane.setBackground(new java.awt.Color(255, 255, 255));
        listPane.setLayout(new java.awt.BorderLayout());
        mainPanel.add(listPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 150, 400, 930));

        sidePanel.setBackground(new java.awt.Color(227, 234, 238));
        sidePanel.setPreferredSize(new java.awt.Dimension(320, 930));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctors.setBackground(new java.awt.Color(0, 113, 197));
        doctors.setOpaque(false);
        doctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doctorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doctorsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                doctorsMousePressed(evt);
            }
        });

        doctorsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        doctorsLabel.setForeground(new java.awt.Color(45, 137, 206));
        doctorsLabel.setText("Doctors");

        javax.swing.GroupLayout doctorsLayout = new javax.swing.GroupLayout(doctors);
        doctors.setLayout(doctorsLayout);
        doctorsLayout.setHorizontalGroup(
            doctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(doctorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        doctorsLayout.setVerticalGroup(
            doctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doctorsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanel.add(doctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        clients.setBackground(new java.awt.Color(0, 113, 197));
        clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientsMousePressed(evt);
            }
        });

        clientsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clientsLabel.setForeground(new java.awt.Color(255, 255, 255));
        clientsLabel.setText("Clients And Tests");

        javax.swing.GroupLayout clientsLayout = new javax.swing.GroupLayout(clients);
        clients.setLayout(clientsLayout);
        clientsLayout.setHorizontalGroup(
            clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(clientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        clientsLayout.setVerticalGroup(
            clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanel.add(clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        results.setBackground(new java.awt.Color(0, 113, 197));
        results.setOpaque(false);
        results.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resultsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resultsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resultsMousePressed(evt);
            }
        });

        resultsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resultsLabel.setForeground(new java.awt.Color(45, 137, 206));
        resultsLabel.setText("Tests Results");

        javax.swing.GroupLayout resultsLayout = new javax.swing.GroupLayout(results);
        results.setLayout(resultsLayout);
        resultsLayout.setHorizontalGroup(
            resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        resultsLayout.setVerticalGroup(
            resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanel.add(results, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        bill.setBackground(new java.awt.Color(0, 113, 197));
        bill.setOpaque(false);
        bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                billMousePressed(evt);
            }
        });

        billLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        billLabel.setForeground(new java.awt.Color(45, 137, 206));
        billLabel.setText("Bill & Payment");

        javax.swing.GroupLayout billLayout = new javax.swing.GroupLayout(bill);
        bill.setLayout(billLayout);
        billLayout.setHorizontalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(billLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        billLayout.setVerticalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanel.add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        mainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 private void mousePress(JPanel panel) {//change color of option panell
        panel.setBackground(new Color(0, 113, 197));
        clients.setOpaque(false);
        results.setOpaque(false);
        doctors.setOpaque(false);
        bill.setOpaque(false);
        panel.setOpaque(true);
    }
    
    private void mousePressLabel(JLabel label) {  // change color of option label(text)
        clientsLabel.setForeground(new Color(45, 137, 206));
        resultsLabel.setForeground(new Color(45, 137, 206));
        billLabel.setForeground(new Color(45, 137, 206));
        doctorsLabel.setForeground(new Color(45, 137, 206));
        label.setForeground(new Color(255, 255, 255));
    }
   
     private void mouseOnOption(JPanel panel, JLabel label) {
        if (panel.isOpaque() == true) {
            return;                                  // already clicked
        }
        panel.setBackground(new Color(0, 174, 239));
        label.setForeground(new Color(255, 255, 255));
        panel.setOpaque(true);
        repaint();
        
    }
    
    private void mouseOffOption(JPanel panel, JLabel label) {
      if(panel.getBackground().getRGB()==new Color(0,113,197).getRGB())
          return;
        panel.setBackground(new Color(0, 113, 197));
        label.setForeground(new Color(45, 137, 206));
        panel.setOpaque(false);
        repaint();
    }
    
    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        try {
            // TODO add your handling code here:
            Thread.sleep(400);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
         btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_blue.png")));

    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
         btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/llljl.PNG")));
    }//GEN-LAST:event_btnExitMouseExited

    private void doctorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMouseEntered
        mouseOnOption(doctors, doctorsLabel);
    }//GEN-LAST:event_doctorsMouseEntered

    private void doctorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMouseExited
        mouseOffOption(doctors, doctorsLabel);

    }//GEN-LAST:event_doctorsMouseExited

    private void doctorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMousePressed
        // TODO add your handling code here:
        mousePress(doctors);
        mousePressLabel(doctorsLabel);
          //removing panels
        mainPane.removeAll();
        mainPane.repaint();
        mainPane.revalidate();
        
        //adding new panel
        mainPane.add(new DoctorsPage());
        mainPane.repaint();
        mainPane.revalidate();
        
        repaint();
        repaint();
    }//GEN-LAST:event_doctorsMousePressed

    private void clientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsMouseEntered
        mouseOnOption(clients, clientsLabel);
    }//GEN-LAST:event_clientsMouseEntered

    private void clientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsMouseExited
        mouseOffOption(clients, clientsLabel);
    }//GEN-LAST:event_clientsMouseExited

    private void clientsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsMousePressed

        mousePress(clients);
        mousePressLabel(clientsLabel);
          //removing panels
        mainPane.removeAll();
        mainPane.repaint();
        mainPane.revalidate();
        
        //adding new panel
        mainPane.add(new ClientPage());
        mainPane.repaint();
        mainPane.revalidate();
        
        repaint();
        repaint();
    }//GEN-LAST:event_clientsMousePressed

    private void resultsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsMouseEntered
        mouseOnOption(results, resultsLabel);
    }//GEN-LAST:event_resultsMouseEntered

    private void resultsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsMouseExited
        mouseOffOption(results, resultsLabel);
    }//GEN-LAST:event_resultsMouseExited

    private void resultsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsMousePressed

        mousePress(results);
        mousePressLabel(resultsLabel);
        //removing panels
        mainPane.removeAll();
        mainPane.repaint();
        mainPane.revalidate();
        
        //adding new panel
        mainPane.add(new TestsPage());
        mainPane.repaint();
        mainPane.revalidate();
        
        repaint();
    }//GEN-LAST:event_resultsMousePressed

    private void billMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMouseEntered
        mouseOnOption(bill, billLabel);
    }//GEN-LAST:event_billMouseEntered

    private void billMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMouseExited
        mouseOffOption(bill, billLabel);
    }//GEN-LAST:event_billMouseExited

    private void billMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMousePressed

        mousePress(bill);
        mousePressLabel(billLabel);
          //removing panels
        mainPane.removeAll();
        mainPane.repaint();
        mainPane.revalidate();
        
        //adding new panel
        mainPane.add(new BillsPage());
        mainPane.repaint();
        mainPane.revalidate();
        
        repaint();
        repaint();
    }//GEN-LAST:event_billMousePressed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
             /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bill;
    private javax.swing.JLabel billLabel;
    private javax.swing.JLabel btnExit;
    private javax.swing.JPanel clients;
    private javax.swing.JLabel clientsLabel;
    private javax.swing.JPanel doctors;
    private javax.swing.JLabel doctorsLabel;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator line;
    private javax.swing.JPanel listPane;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel results;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
